spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: blog
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
debug: false
server:
port: 8080